spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: portail
  datasource:
    url: jdbc:mysql://localhost:3306/courses
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update